server:
  port: 8082
  host: localhost

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: forum
  sslmode: disable
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: 300s

jwt:
  secret_key: "your-secret-key-here" # Замените на реальный секретный ключ
  token_lifetime: 168h # 7 дней 